name: Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  Develop:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Git config
        uses: ./.github/actions/git-config
      - name: Git tag
        id: tag
        run: echo "TAG_NAME=$(npm version prerelease --preid=rc)" >> $GITHUB_ENV
      - name: Manfiest version amend
        run: node ./scripts/syncManifestVersion.js && git add -A && git commit --amend --no-edit
      - name: Git push
        run: |
          git push
          git push --tags
      - name: Dotenv config
        run: |
          touch .env
          echo DISCORD_WEBHOOK=\"${{ secrets.DISCORD_WEBHOOK }}\" >> .env
      - name: Build
        uses: ./.github/actions/build
      - name: Pre-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: true
          generate_release_notes: true
          files: |
            ./dist/PockestHelper.zip
