name: git-config
description: Configure Git for GitHub Actions Bot
runs:
  using: composite
  steps:
    - run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      shell: bash