name: Develop

on:
  push:
    branches:
      - develop
      - feature/ci-auto-tagging

permissions:
  contents: write

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: ./.github/actions/git-config
      # - name: Git Tag
      #   run: npm run release:rc
      # - name: Git push
      #   run: |
      #     git push
      #     git push --tags
  Release:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      # - name: Pre-release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     prerelease: true
      #     generate_release_notes: true
      #     files: |
      #       ./dist/PockestHelper.zip
