name: Pre-release

on:
  push:
    tags:
      - "v*-rc*"

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            ./dist/PockestHelper.zip
