name: Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DISCORD_WEBHOOK: ${{ vars.DISCORD_WEBHOOK }}

jobs:
  Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Git config
        uses: ./.github/actions/git-config

      - name: Git tag and push
        id: tag
        run: |
          echo "TAG_NAME=$(npm version patch)" >> $GITHUB_ENV
          git push
          git push --tags

      - name: Dotenv config
        run: |
          touch .env
          echo DISCORD_WEBHOOK=\"${{ vars.DISCORD_WEBHOOK }}\" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip file
        run: echo "ZIP_FILE=$(node ./scripts/zipExtension.js)" >> $GITHUB_ENV

      - name: Publish/Build Web Extension
        run: |
          npm i -g web-ext
          web-ext sign -s ./dist --channel unlisted --api-key ${{ secrets.JWT_ISSUER }} --api-secret ${{ secrets.JWT_SECRET }} -a ./dist
          echo "XPI_FILE=$(node ./scripts/xpiExtension.js)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ env.ZIP_FILE }}
            ${{ env.XPI_FILE }}
