name: Production

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  Production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Git config
        uses: ./.github/actions/git-config
      - name: Git tag and push
        id: tag
        run: |
          echo "TAG_NAME=$(npm version patch)" >> $GITHUB_ENV
          git push
          git push --tags
      - name: Dotenv config
        run: |
          touch .env
          echo DISCORD_WEBHOOK=\"${{ secrets.DISCORD_WEBHOOK }}\" >> .env
      - name: Build
        uses: ./.github/actions/build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          prerelease: false
          generate_release_notes: true
          files: |
            ./dist/PockestHelper.zip
