name: Release

on:
  push:
    tags:
      - "v*"
      - "!v*-rc*"

permissions:
  contents: write

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          generate_release_notes: true
          files: |
            ./dist/PockestHelper.zip

