name: Tag (develop)

on:
  push:
    branches:
      - develop
      - feature/ci-auto-tagging

permissions:
  contents: write

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Git Tag
        run: npm run release:rc
      - name: Git push
        run: |
          git push
          git push --tags
