---
name: "tagged-pre-release"

on:
  push:
    tags:
      - "v*-rc*"

jobs:
  tagged-release:
    name: "Tagged Pre-Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: "Install dependencies"
        run: |
          npm ci
      - name: "Build"
        run: |
          npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            ./dist/PockestHelper.zip
